---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-1-statefulset
spec:
  selector:
    matchLabels:
      app: node-app-4
  serviceName: node-app-4
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app-4
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: node-app-4
          image: docker.io/mohandasspat/node-app-3
          ports:
            - containerPort: 4000
              name: http
          volumeMounts:
            - name: www
              mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 500Mi